stages:
  - test
  - moban

jobs:
  include:
    - python: 3.6
      language: python
      stage: moban
      env: false
      cache: pip
      before_install: false
      install: pip install moban
      before_script: false
      script: .ci/check_moban.sh
      after_success: false
    - stage: test
      language: node_js
      node_js: 8
      cache:
        directories:
          - "node_modules"
      before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - sleep 3
      script:
        - npm run test
        - script/build.sh

notifications:
  email: false
  webhooks: https://www.travisbuddy.com/
  on_success: never
