# `sudo:false` for faster builds.
sudo: false
language: node_js
node_js:  # must have multiple entries otherwise it is ignored
  - 8
  - 9

cache:
  directories:
    - $XDG_CACHE_HOME/pip
    - $XDG_CACHE_HOME/npm
    - $XDG_CACHE_HOME/node_modules

.disable_global: &disable_global
  node_js: false
  cache: false
  before_install: false
  install: false
  before_script: false
  script: false
  after_script: false
  after_success: false
  before_deploy: false
  deploy: false

stages:
  - lint
  - test
  - moban

env:
  global:
    - DISPLAY=:99.0
    - XDG_CONFIG_HOME=$HOME/.config
    - XDG_DATA_HOME=$HOME/.local/share
    - XDG_CACHE_HOME=$HOME/.cache
    - XDG_RUNTIME_DIR=/tmp
    - NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/config
    - NPM_CONFIG_CACHE=$XDG_CACHE_HOME/npm
    - NPM_CONFIG_TMP=$XDG_RUNTIME_DIR/npm
    - NODE_PATH=$XDG_CACHE_HOME/node_modules
    - PATH=$PATH:$NODE_PATH/.bin

jobs:
  include:
    - <<: *disable_global
      stage: moban
      language: python
      python: 3.6
      cache: pip
      install: pip install moban
      script: .ci/check_moban.sh

    - <<: *disable_global
      stage: lint
      language: python
      python: 3.6
      install:
        - pip install coala-bears
        - mkdir -p $XDG_CACHE_HOME/node_modules/
        - ln -s $XDG_CACHE_HOME/node_modules/ .
        - npm install --prefix=$XDG_CACHE_HOME .
      script: coala --non-interactive -V

# Needed for Firefox
before_script:
  - sh -e /etc/init.d/xvfb start
  - sleep 3  # give xvfb some time to start

script:
  - script/build.sh
  - npm run test

after_script:
  # Remove the symlink after node is finished
  - rm node_modules

notifications:
  email: false
  webhooks: https://www.travisbuddy.com/
  on_success: never

# Remove /dist/ from .gitignore
before_deploy:
  - sed -i '/dist\//d' ./.gitignore

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep-history: true
  'on':
    branch: master
