# `sudo:false` for faster builds.
sudo: false
language: node_js
node_js:  # must have multiple entries otherwise it is ignored
  - 8
  - 9

cache:
  directories:
    - $XDG_CACHE_HOME/npm
    - $XDG_CACHE_HOME/node_modules

env:
  global:
    - DISPLAY=:99.0
    - XDG_CONFIG_HOME=$HOME/.config
    - XDG_DATA_HOME=$HOME/.local/share
    - XDG_CACHE_HOME=$HOME/.cache
    - XDG_RUNTIME_DIR=/tmp
    - NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/config
    - NPM_CONFIG_CACHE=$XDG_CACHE_HOME/npm
    - NPM_CONFIG_TMP=$XDG_RUNTIME_DIR/npm
    - NODE_PATH=$XDG_CACHE_HOME/node_modules
    - PATH=$PATH:$NODE_PATH/.bin

jobs:
  include:
    - stage: moban
      language: python
      python: 3.6
      node_js: false
      cache: pip
      before_install: false
      install: pip install moban
      before_script: false
      script: .ci/check_moban.sh
      after_success: false
      deploy: false

before_install:
  - ln -s $NODE_PATH .
  - mkdir -p $XDG_CACHE_HOME/node_modules/
  - cp package.json $XDG_CACHE_HOME

install:
  - (cd $XDG_CACHE_HOME && npm install --no-optional)
  - npm ls

# Needed for Firefox
before_script:
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

script:
  - script/build.sh
  - npm run test

after_script:
  # Remove the symlink after node is finished
  - rm node_modules

notifications:
  email: false
  webhooks: https://www.travisbuddy.com/
  on_success: never

# Remove /dist/ from .gitignore
before_deploy:
  - sed -i '/dist\//d' ./.gitignore

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
